#SPDX-License-Identifier: MIT-0
---
ssh_port: 2002
risky_users:
  - games
  - lp
  - news
  - uucp
  - gopher
  - ftp
  - operator
admin_user: ansible_admin
unused_services:
  - cups
  - avahi-daemon
  - bluetooth
  - ModemManager
  - wpa_supplicant
  - rpcbind