[noeuds]
ansible-noeud1 ansible_host=192.168.149.144
ansible-noeud2 ansible_host=192.168.149.146
ansible-noeud3 ansible_host=192.168.149.148

[webservers]
ansible-noeud1 ansible_host=192.168.149.144

[dbservers]
ansible-noeud2 ansible_host=192.168.149.146

[idsservers]
ansible-noeud3 ansible_host=192.168.149.148

[filebeat_targets:children]
webservers
dbservers
idsservers

[all_servers:children]
webservers
dbservers
idsservers