[noeuds]
ansible-noeud1 ansible_host=192.168.149.134 ansible_port=2002
ansible-noeud2 ansible_host=192.168.149.135 ansible_port=2002
ansible-noeud3 ansible_host=192.168.149.133 ansible_port=2002

[webservers]
ansible-noeud1 ansible_host=192.168.149.134 ansible_port=2002

[dbservers]
ansible-noeud2 ansible_host=192.168.149.135 ansible_port=2002

[idsservers]
ansible-noeud3 ansible_host=192.168.149.133 ansible_port=2002

[filebeat_targets:children]
webservers
dbservers
idsservers

[all_servers:children]
webservers
dbservers
idsservers